image: proboci/ubuntu-14.04-lamp:php7.1-nightly
assets:
  - d7testsite.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    drupalVersion: 7
    database: d7testsite.sql.gz
    databaseGzipped: true
    databaseUpdates: false
    revertFeatures: false
    clearCaches: true
    phpIniOptions:
      curl.cainfo: /root/cacert.pem
  - name: Generate login link.
    command: "drush --root='/var/www/html/' uli"
  - name: Test BUILD_URL VAR.
    plugin: Script
    script:
      - printenv
  - name: Setup pem file.
    plugin: Script
    script:
      - wget https://curl.haxx.se/ca/cacert.pem -o /root/cacert.pem
      - cp /etc/php/7.1/apache2/conf.d/99-probo-settings.ini /etc/php/7.1/cli/conf.d/99-probo-settings.ini
      - apache2ctl graceful
      - curl -I https://d9306af3-28c3-4501-a2d4-ca6340df3779.probo.build
