image: proboci/ubuntu-16.04-lamp:php-7.1
assets:     
  - d7testsite.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    drupalVersion: 7
    database: d7testsite.sql.gz
    databaseGzipped: true
    databaseUpdates: false
    revertFeatures: false
    clearCaches: true
  - name: Create Solr instance...
    command: "sudo -u solr -- /opt/solr/bin/solr create -c drupal7 -d /opt/solr/search_api_solr/solr-conf/6.x"
