image: proboci/ubuntu-14.04-lamp:php7.0-nightly
assets:     
  - d7testsite.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    drupalVersion: 7
    database: d7testsite.sql.gz
    databaseGzipped: true
    databaseUpdates: false
    revertFeatures: false
    clearCaches: true
  - name: Generate login link
    command: "drush --root='/var/www/html/' uli"
  - name: Test BUILD_URL VAR
    plugin: Script
    script:
      - echo "${BUILD_URL}"
      - var_dump(get_defined_vars());
