image: proboci/ubuntu-16.04-lamp:php7.2-nightly
assets:     
  - d7testsite.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    drupalVersion: 7
    database: d7testsite.sql.gz
    databaseGzipped: true
    databaseUpdates: false
    revertFeatures: false
    clearCaches: true
  - name: Generate login link
    command: "drush --root='/var/www/html/' uli"
  - name: Check versions.
    plugin: Script
    script:
      - php --version
      - mysql --version
      - lsb_release -a
